## Exercícios

**Criar a Seguinte Função znorm = x-min(x) / max (x) - min (x)**
                              

In [ ]:
import numpy as np
import random as rnd
import pandas as pd

**Criar 2 Vetores: vetorA (nrs de 1 a 20), vetorB(números aleatórios entre 1 e 20)**

In [ ]:
vetorA = np.array(list(range(1,21)))
vetorA

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
vetorB = np.array(rnd.sample(range(1,21), 20))
vetorB

array([ 5, 15,  7,  4,  8, 16,  1,  2, 11, 12, 13, 18, 10, 19,  3, 20, 17,
       14,  6,  9])

**Aplique a função criada nos vetores. O que ocorreu? Salve os resultados em novos vetores**





In [ ]:
znorm = (np.array(vetorA) - min(np.array(vetorA))) / (max(np.array(vetorA)) - min(np.array(vetorA)))
znormrounda = []
for number in znorm:
  znormrounda.append(round(number, 3))
  
print(znormrounda)

[0.0, 0.053, 0.105, 0.158, 0.211, 0.263, 0.316, 0.368, 0.421, 0.474, 0.526, 0.579, 0.632, 0.684, 0.737, 0.789, 0.842, 0.895, 0.947, 1.0]


In [ ]:
znormb = (np.array(vetorB) - min(np.array(vetorB))) / (max(np.array(vetorB)) - min(np.array(vetorB)))
znormroundb = []
for number in znormb:
  znormroundb.append(round(number, 3))
  
print(znormroundb)

[0.211, 0.737, 0.316, 0.158, 0.368, 0.789, 0.0, 0.053, 0.526, 0.579, 0.632, 0.895, 0.474, 0.947, 0.105, 1.0, 0.842, 0.684, 0.263, 0.421]


In [ ]:
vtresultA = np.array(znormrounda)
print(vtresultA)

vtresultB = np.array(znormroundb)
print(vtresultB)

[0.    0.053 0.105 0.158 0.211 0.263 0.316 0.368 0.421 0.474 0.526 0.579
 0.632 0.684 0.737 0.789 0.842 0.895 0.947 1.   ]
[0.211 0.737 0.316 0.158 0.368 0.789 0.    0.053 0.526 0.579 0.632 0.895
 0.474 0.947 0.105 1.    0.842 0.684 0.263 0.421]


**Crie as matrizes matrixAB(20,2) e matrixAB_norm(20,2) utilizando os vetores criados anteriormente.**

In [ ]:
m1 = np.array(vetorA)
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
m2 = np.array(vetorB)
m2

array([ 5, 15,  7,  4,  8, 16,  1,  2, 11, 12, 13, 18, 10, 19,  3, 20, 17,
       14,  6,  9])

In [26]:
matrizab = np.array([[m1], [m2]])
matrizab

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
         17, 18, 19, 20]],

       [[ 5, 15,  7,  4,  8, 16,  1,  2, 11, 12, 13, 18, 10, 19,  3, 20,
         17, 14,  6,  9]]])

In [34]:
matrizabnorm = np.array([[vtresultA], [vtresultB]])
matrizabnorm

array([[[0.   , 0.053, 0.105, 0.158, 0.211, 0.263, 0.316, 0.368, 0.421,
         0.474, 0.526, 0.579, 0.632, 0.684, 0.737, 0.789, 0.842, 0.895,
         0.947, 1.   ]],

       [[0.211, 0.737, 0.316, 0.158, 0.368, 0.789, 0.   , 0.053, 0.526,
         0.579, 0.632, 0.895, 0.474, 0.947, 0.105, 1.   , 0.842, 0.684,
         0.263, 0.421]]])

**Aplique as operações “*” e “dot” nas matrizes. Quais os resultados obtidos?**

In [35]:
matrizab*matrizabnorm

array([[[ 0.   ,  0.106,  0.315,  0.632,  1.055,  1.578,  2.212,  2.944,
          3.789,  4.74 ,  5.786,  6.948,  8.216,  9.576, 11.055, 12.624,
         14.314, 16.11 , 17.993, 20.   ]],

       [[ 1.055, 11.055,  2.212,  0.632,  2.944, 12.624,  0.   ,  0.106,
          5.786,  6.948,  8.216, 16.11 ,  4.74 , 17.993,  0.315, 20.   ,
         14.314,  9.576,  1.578,  3.789]]])

In [36]:
np.dot(vtresultA, vtresultB)

5.553299000000001