## Aula 02

In [ ]:
import numpy as np
import random as rnd

Operações Básicas

In [ ]:
# soma
6+5

11

In [ ]:
# subtração 
9-5

4

In [ ]:
# multiplicação 
2*3

6

In [ ]:
# divisão
8/2

4.0

In [ ]:
# potencia
5**2

25

In [ ]:
# logaritimo
np.log(5)

1.6094379124341003

In [ ]:
# exponencial
np.exp(7)

1096.6331584284585

## Criar Função

In [ ]:
def funcao(a, b):
  res = a*b
  return res

funcao (8,2)

16

In [ ]:
def funcao2(a, potencia):
  res = a**b
  return res

funcao2 (2,3)


512

## Criação de Lista Customizada / Sequencial / Números Aleatórios

In [ ]:
# lista customizada
lista1 = [1,5,10]
lista1

[1, 5, 10]

In [ ]:
# lista sequencial
lista2 = list(range(2,8))
lista2


[2, 3, 4, 5, 6, 7]

## Loops

In [ ]:
for i in range(5):
  print(i)

0
1
2
3
4


In [ ]:
for nome in ['al', 'ci', 'des']:
  print(nome)

al
ci
des


In [ ]:
#loop para criar sequencia de números aleatórios
for i in range(5):

  print(round(rnd.uniform(0, 1), 4))

0.309
0.6816
0.3092
0.5101
0.3685


In [ ]:
#loop para criar lista de números aleatórios
lista_aleatoria = [round(rnd.uniform(0, 1), 2) for i in range(5)]
lista_aleatoria



[0.79, 0.45, 0.38, 0.3, 0.38]

In [ ]:
# criar lista de números aleatórios inteiros
megadavirada = rnd.sample(range(1,61), 6)
megadavirada

[24, 13, 33, 27, 17, 22]

## Operações com Listas Numpy

In [ ]:
# somar listas
a = [2, 3]
b = [5, 6]
a+b

[2, 3, 5, 6]

In [ ]:
# somar listas numpy
a_np = np.array(a)
a_np

array([2, 3])

In [ ]:
b_np = np.array(b)
b_np

array([5, 6])

In [ ]:
# soma
a_np+b_np

array([7, 9])

In [ ]:
#subtração
a_np-b_np

array([-3, -3])

In [ ]:
# multiplicação
a_np*b_np

array([10, 18])

In [ ]:
# divisão
a_np/b_np

array([0.4, 0.5])

## Operações com Matrizes

In [ ]:
# criar matriz numpy
A = np.array([[2,3], [5,6]])
A

array([[2, 3],
       [5, 6]])

In [ ]:
B = np.array([[7,2], [4,3]])
B

array([[7, 2],
       [4, 3]])

In [ ]:
# Soma
A+B

array([[9, 5],
       [9, 9]])

In [ ]:
# Subtração
A-B

array([[-5,  1],
       [ 1,  3]])

In [ ]:
# Multiplicação de elementos
A*B

array([[14,  6],
       [20, 18]])

In [ ]:
# Multiplicação de Matriz
A.dot(B)

array([[26, 13],
       [59, 28]])