<a href="https://colab.research.google.com/github/cesaroliveiragoes/Statistics-for-Data-Science/blob/main/exercicio_01_resolucao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Resolução

In [ ]:
import numpy as np
import random as rnd

Questão 1

In [ ]:
def znorm(x):
  res = (x-min(x)) / (max(x) - min(x))
  return res

In [ ]:
znorm (np.array([1, 4, 10]))

array([0.        , 0.33333333, 1.        ])

Questao 2

In [ ]:
vetorA = np.array(list(range(1,21)))
vetorA

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
vetorB = np.array(rnd.sample(range(1,21), 20))
vetorB

array([18, 19, 14,  7, 17,  4, 16,  8, 20,  6,  9, 13,  1,  2,  3,  5, 12,
       11, 10, 15])

Questão 3

In [ ]:
vetorA_norm = znorm(vetorA)
vetorA_norm

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
vetorB_norm = znorm(vetorB)
vetorB_norm

array([0.89473684, 0.94736842, 0.68421053, 0.31578947, 0.84210526,
       0.15789474, 0.78947368, 0.36842105, 1.        , 0.26315789,
       0.42105263, 0.63157895, 0.        , 0.05263158, 0.10526316,
       0.21052632, 0.57894737, 0.52631579, 0.47368421, 0.73684211])

Questao 4

In [ ]:
#sem transpose
np.array([vetorA, vetorB]).shape


(2, 20)

In [ ]:
#com transpose
matrizAB = np.transpose([vetorA, vetorB])
matrizAB

array([[ 1, 18],
       [ 2, 19],
       [ 3, 14],
       [ 4,  7],
       [ 5, 17],
       [ 6,  4],
       [ 7, 16],
       [ 8,  8],
       [ 9, 20],
       [10,  6],
       [11,  9],
       [12, 13],
       [13,  1],
       [14,  2],
       [15,  3],
       [16,  5],
       [17, 12],
       [18, 11],
       [19, 10],
       [20, 15]])

In [ ]:
matrizABnorm = np.transpose([vetorA_norm, vetorB_norm])
matrizABnorm

array([[0.        , 0.89473684],
       [0.05263158, 0.94736842],
       [0.10526316, 0.68421053],
       [0.15789474, 0.31578947],
       [0.21052632, 0.84210526],
       [0.26315789, 0.15789474],
       [0.31578947, 0.78947368],
       [0.36842105, 0.36842105],
       [0.42105263, 1.        ],
       [0.47368421, 0.26315789],
       [0.52631579, 0.42105263],
       [0.57894737, 0.63157895],
       [0.63157895, 0.        ],
       [0.68421053, 0.05263158],
       [0.73684211, 0.10526316],
       [0.78947368, 0.21052632],
       [0.84210526, 0.57894737],
       [0.89473684, 0.52631579],
       [0.94736842, 0.47368421],
       [1.        , 0.73684211]])

Questão 5

In [ ]:
matrizAB * matrizABnorm

array([[ 0.        , 16.10526316],
       [ 0.10526316, 18.        ],
       [ 0.31578947,  9.57894737],
       [ 0.63157895,  2.21052632],
       [ 1.05263158, 14.31578947],
       [ 1.57894737,  0.63157895],
       [ 2.21052632, 12.63157895],
       [ 2.94736842,  2.94736842],
       [ 3.78947368, 20.        ],
       [ 4.73684211,  1.57894737],
       [ 5.78947368,  3.78947368],
       [ 6.94736842,  8.21052632],
       [ 8.21052632,  0.        ],
       [ 9.57894737,  0.10526316],
       [11.05263158,  0.31578947],
       [12.63157895,  1.05263158],
       [14.31578947,  6.94736842],
       [16.10526316,  5.78947368],
       [18.        ,  4.73684211],
       [20.        , 11.05263158]])

In [ ]:
#dot - forma 1
matrizAB.dot(np.transpose(matrizABnorm)).shape


(20, 20)

In [ ]:
#dot - forma 2
np.transpose(matrizAB).dot(matrizABnorm)

array([[140.        ,  92.31578947],
       [ 92.31578947, 140.        ]])