<a href="https://colab.research.google.com/github/cesaroliveiragoes/Statistics-for-Data-Science/blob/main/exercicios_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Exercícios

**Criar a Seguinte Função znorm = x-min(x) / max (x) - min (x)**
                              

In [ ]:
import numpy as np
import random as rnd
import pandas as pd

**Criar 2 Vetores: vetorA (nrs de 1 a 20), vetorB(números aleatórios entre 1 e 20)**

In [ ]:
vetorA = np.array(list(range(1,21)))
vetorA

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
vetorB = np.array(rnd.sample(range(1,21), 20))
vetorB

array([10, 13,  5, 18, 15,  9,  2,  8,  1,  3, 12,  4, 20, 16, 19, 17,  6,
        7, 14, 11])

**Aplique a função criada nos vetores. O que ocorreu? Salve os resultados em novos vetores**





In [ ]:
znorm = (np.array(vetorA) - min(np.array(vetorA))) / (max(np.array(vetorA)) - min(np.array(vetorA)))
znormrounda = []
for number in znorm:
  znormrounda.append(round(number, 3))

print(znormrounda)

[0.0, 0.053, 0.105, 0.158, 0.211, 0.263, 0.316, 0.368, 0.421, 0.474, 0.526, 0.579, 0.632, 0.684, 0.737, 0.789, 0.842, 0.895, 0.947, 1.0]


In [ ]:
znormb = (np.array(vetorB) - min(np.array(vetorB))) / (max(np.array(vetorB)) - min(np.array(vetorB)))
znormroundb = []
for number in znormb:
  znormroundb.append(round(number, 3))

print(znormroundb)

[0.474, 0.632, 0.211, 0.895, 0.737, 0.421, 0.053, 0.368, 0.0, 0.105, 0.579, 0.158, 1.0, 0.789, 0.947, 0.842, 0.263, 0.316, 0.684, 0.526]


In [ ]:
vtresultA = np.array(znormrounda)
print(vtresultA)

vtresultB = np.array(znormroundb)
print(vtresultB)

[0.    0.053 0.105 0.158 0.211 0.263 0.316 0.368 0.421 0.474 0.526 0.579
 0.632 0.684 0.737 0.789 0.842 0.895 0.947 1.   ]
[0.474 0.632 0.211 0.895 0.737 0.421 0.053 0.368 0.    0.105 0.579 0.158
 1.    0.789 0.947 0.842 0.263 0.316 0.684 0.526]


**Crie as matrizes matrixAB(20,2) e matrixAB_norm(20,2) utilizando os vetores criados anteriormente.**

In [ ]:
m1 = np.array(vetorA)
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
m2 = np.array(vetorB)
m2

array([10, 13,  5, 18, 15,  9,  2,  8,  1,  3, 12,  4, 20, 16, 19, 17,  6,
        7, 14, 11])

In [ ]:
matrizab = np.transpose([m1, m2])
matrizab

array([[ 1, 10],
       [ 2, 13],
       [ 3,  5],
       [ 4, 18],
       [ 5, 15],
       [ 6,  9],
       [ 7,  2],
       [ 8,  8],
       [ 9,  1],
       [10,  3],
       [11, 12],
       [12,  4],
       [13, 20],
       [14, 16],
       [15, 19],
       [16, 17],
       [17,  6],
       [18,  7],
       [19, 14],
       [20, 11]])

In [ ]:
matrizabnorm = np.array([[vtresultA], [vtresultB]])
matrizabnorm

array([[[0.   , 0.053, 0.105, 0.158, 0.211, 0.263, 0.316, 0.368, 0.421,
         0.474, 0.526, 0.579, 0.632, 0.684, 0.737, 0.789, 0.842, 0.895,
         0.947, 1.   ]],

       [[0.474, 0.632, 0.211, 0.895, 0.737, 0.421, 0.053, 0.368, 0.   ,
         0.105, 0.579, 0.158, 1.   , 0.789, 0.947, 0.842, 0.263, 0.316,
         0.684, 0.526]]])

**Aplique as operações “*” e “dot” nas matrizes. Quais os resultados obtidos?**

In [ ]:
matrizab*matrizabnorm

array([[[ 0.   ,  0.106,  0.315,  0.632,  1.055,  1.578,  2.212,  2.944,
          3.789,  4.74 ,  5.786,  6.948,  8.216,  9.576, 11.055, 12.624,
         14.314, 16.11 , 17.993, 20.   ]],

       [[ 4.74 ,  8.216,  1.055, 16.11 , 11.055,  3.789,  0.106,  2.944,
          0.   ,  0.315,  6.948,  0.632, 20.   , 12.624, 17.993, 14.314,
          1.578,  2.212,  9.576,  5.786]]])

In [ ]:
np.dot(vtresultA, vtresultB)

5.273235999999999

#Aula 02

In [ ]:
dados = pd.read_csv('dados_1997_2011_paises_csv.csv', encoding = 'latin1', sep = ';', decimal = ',')
dados

pais   ano     idh  corrupcao_indice  competitividade_indice  \
0    África do Sul  1997  0.6328                56                   44.54   
1    África do Sul  1998  0.6272                57                   31.11   
2    África do Sul  1999  0.6216                50                   43.90   
3    África do Sul  2000  0.6160                52                   51.52   
4    África do Sul  2001  0.6126                50                   45.12   
..             ...   ...     ...               ...                     ...   
280    Reino Unido  2007  0.8560                86                   75.45   
281    Reino Unido  2008  0.8600                86                   71.90   
282    Reino Unido  2009  0.8600                84                   76.07   
283    Reino Unido  2010  0.8620                77                   76.81   
284    Reino Unido  2011  0.8630                77                   80.28   

     globalizacao_indice           pib    populacao  
0               52.60298  1.488142e+08  43353.63200  
1               54.51911  1.342956e+08  43961.92400  
2               61.04379  1.331836e+08  44526.27200  
3               62.47182  1.328776e+08  45064.09800  
4               62.04144  1.184790e+08  45576.21500  
..                   ...           ...          ...  
280             82.12010  1.448770e+06  61337.36992  
281             81.67998  1.447825e+06  61731.27576  
282             79.31000  1.377247e+06  62086.03336  
283             80.18000  1.395893e+06  62438.13815  
284             81.68000  1.500045e+06  62262.00000  

[285 rows x 8 columns]

2)

In [ ]:
def znorm(x):
  res = (x-min(x)) / (max(x) - min(x))
  return res

3)

In [ ]:
z_pop = dados['populacao']
z_pop

0      43353.63200
1      43961.92400
2      44526.27200
3      45064.09800
4      45576.21500
          ...     
280    61337.36992
281    61731.27576
282    62086.03336
283    62438.13815
284    62262.00000
Name: populacao, Length: 285, dtype: float64

In [ ]:
z_pib = dados['pib']
z_pib

0      1.488142e+08
1      1.342956e+08
2      1.331836e+08
3      1.328776e+08
4      1.184790e+08
           ...     
280    1.448770e+06
281    1.447825e+06
282    1.377247e+06
283    1.395893e+06
284    1.500045e+06
Name: pib, Length: 285, dtype: float64

In [ ]:
z_popnorm = znorm(z_pop)
z_popnorm

0      0.029461
1      0.029914
2      0.030334
3      0.030735
4      0.031116
         ...   
280    0.042846
281    0.043140
282    0.043404
283    0.043666
284    0.043535
Name: populacao, Length: 285, dtype: float64

In [ ]:
z_pibnorm = znorm(z_pib)
z_pibnorm

0      0.010181
1      0.009186
2      0.009109
3      0.009088
4      0.008101
         ...   
280    0.000078
281    0.000078
282    0.000073
283    0.000074
284    0.000081
Name: pib, Length: 285, dtype: float64

4) Selecionar os países que tem IDH maior que 0.9 em 2008


In [ ]:
dados[dados['idh'] > 0.9]

pais   ano     idh  corrupcao_indice  competitividade_indice  \
25         Alemanha  2007  0.9010                82                   78.02   
26         Alemanha  2008  0.9020                80                   74.74   
28         Alemanha  2010  0.9030                79                   82.73   
29         Alemanha  2011  0.9050                80                   87.82   
32        Austrália  1999  0.9026                89                   76.78   
33        Austrália  2000  0.9060                87                   78.36   
34        Austrália  2001  0.9084                87                   75.30   
35        Austrália  2002  0.9108                83                   73.27   
36        Austrália  2003  0.9132                85                   80.62   
37        Austrália  2004  0.9156                86                   86.05   
38        Austrália  2005  0.9180                88                   81.98   
39        Austrália  2006  0.9200                88                   82.50   
40        Austrália  2007  0.9220                88                   82.39   
41        Austrália  2008  0.9240                87                   83.50   
42        Austrália  2009  0.9260                86                   88.93   
43        Austrália  2010  0.9270                87                   92.17   
44        Austrália  2011  0.9290                87                   89.26   
86           Canadá  2008  0.9030                85                   82.85   
87           Canadá  2009  0.9030                87                   88.71   
88           Canadá  2010  0.9070                87                   90.46   
89           Canadá  2011  0.9080                87                   90.78   
157  Estados Unidos  2004  0.9010                77                  100.00   
158  Estados Unidos  2005  0.9020                75                  100.00   
159  Estados Unidos  2006  0.9040                75                  100.00   
160  Estados Unidos  2007  0.9050                76                  100.00   
161  Estados Unidos  2008  0.9070                73                  100.00   
162  Estados Unidos  2009  0.9060                72                  100.00   
163  Estados Unidos  2010  0.9080                73                   99.09   
164  Estados Unidos  2011  0.9130                71                   99.09   
190         Holanda  2007  0.9020                86                   85.86   
191         Holanda  2008  0.9040                87                   80.48   
192         Holanda  2009  0.9050                90                   87.76   
193         Holanda  2010  0.9090                89                   85.65   
194         Holanda  2011  0.9100                89                   85.71   
239           Japão  2011  0.9010                77                   75.21   

     globalizacao_indice           pib     populacao  
25              86.00454  3.323807e+09   82500.62788  
26              85.10198  3.623686e+09   82328.58583  
28              84.16000  3.280530e+09   81906.32178  
29              85.10000  3.577031e+09   81844.00000  
32              80.88444  3.902087e+08   18829.98225  
33              82.07458  4.169233e+08   19052.91407  
34              82.54441  3.804277e+08   19293.98163  
35              81.79132  3.972394e+08   19534.65920  
36              82.30564  4.684688e+08   19766.25789  
37              82.23457  6.152760e+08   19994.78963  
38              82.03082  6.960337e+08   20232.05724  
39              82.89672  7.493164e+08   20489.17957  
40              83.23593  8.568164e+08   20749.32886  
41              81.40752  1.039415e+09   21007.01018  
42              80.49000  9.248431e+08   21262.33754  
43              83.82000  1.131623e+09   21515.44693  
44              81.40000  1.371764e+09   22708.00000  
86              85.80734  1.502678e+09   33212.69600  
87              86.32000  1.337578e+09   33487.20800  
88              88.24000  1.577040e+09   33759.74200  
89             