<a href="https://colab.research.google.com/github/cesaroliveiragoes/Statistics-for-Data-Science/blob/main/Global_Solution_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def read_file(filepath):
    # Função que lê o conteúdo de um arquivo.

    # Parâmetros - filepath: O caminho para o arquivo a ser lido.

    with open(filepath) as f:
        # Abre o arquivo especificado pelo caminho 'filepath'.
        str_text = f.read()
        # Lê o conteúdo do arquivo e armazena na variável 'str_text'.

    return str_text
    # Retorna o conteúdo do arquivo como uma string.

In [ ]:
read_file('/content/melville-moby_dick.txt')
# Retorna o conteúdo do arquivo como uma string.

FileNotFoundError: ignored

In [ ]:
import spacy

nlp = spacy.load('en_core_web_sm', disable=['parser', 'tagger', 'ner'])
# Carrega o modelo do Spacy para processamento de texto em inglês.

nlp.max_length = 1198623
# Define o comprimento máximo de texto que o Spacy pode processar.

In [ ]:
def separate_punc(doc_text):
    # Função para separar pontuações de um texto.

    # Parâmetros - doc_text: O texto a ser processado.

    tokens = nlp(doc_text)
    # Utiliza o spaCy para processar o texto e extrair os tokens.

    words = []
 # Cria uma lista vazia para armazenar as palavras sem pontuações.

    for token in tokens:
    # Itera sobre cada token no texto processado.

        if token.text not in '\n\n \n\n\n!"-#$%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n ':
          # Verifica se o texto do token não está presente na string de pontuações.

            words.append(token.text.lower())
             # Converte o texto do token para letras minúsculas e adiciona à lista de palavras.

    return words
        # Retorna a lista de palavras sem pontuações.


In [ ]:
d = read_file("/content/melville-moby_dick.txt")
# Lê o conteúdo do arquivo especificado no caminho e armazena na variável 'd'.
tokens = separate_punc(d)
# Separa as pontuações do texto contido em 'd' e retorna uma lista de palavras em letras minúsculas, sem as pontuações armazenando na variável 'tokens'.


In [ ]:
tokens
# Chama a variável 'tokens'

In [ ]:
len(tokens)
# Retorna a quantidade de palavras na variável 'tokens'.

NameError: ignored

In [ ]:
max = int(len(tokens) * 0.75)
# Calcula o valor máximo como 75% do tamanho da lista de tokens.

In [ ]:
tokens = tokens[:max]
# Seleciona apenas os primeiros "max" elementos da lista de tokens.

In [ ]:
train_len = 25+1
# Define o tamanho do treinamento como 25 palavras mais 1 (total de 26 palavras).

text_sequences = []
# Cria uma lista vazia.

for i in range(train_len, len(tokens)):
  # Itera sobre os índices de train_len até o final da lista de tokens.

    seq = tokens[i-train_len:i]
      # Extrai a sequência de palavras de tamanho train_len a partir do índice i.

    text_sequences.append(seq)
      # Adiciona a sequência à lista de text_sequences.

In [ ]:
' '.join(text_sequences[0])
# Concatena os elementos da primeira sequência de tokens usando um espaço como separador.

'chapter 1 loomings call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to'

In [ ]:
' '.join(text_sequences[1])
# Concatena os elementos da segunda sequência de tokens usando um espaço como separador.

'1 loomings call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest'

In [ ]:
' '.join(text_sequences[2])
# Concatena os elementos da terceira sequência de tokens usando um espaço como separador.

'loomings call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me'

In [ ]:
len(text_sequences)
# Retorna a quantidade de palavras na variável 'text_sequences'.

161005

In [ ]:
max = int(len(text_sequences) * 0.75)
# Calcula o valor máximo como 75% do tamanho da variável 'text_sequences'.

In [ ]:
text_sequences=text_sequences[:max]
# Seleciona apenas os primeiros "max" elementos da lista 'text_sequences'.

In [ ]:
from keras.preprocessing.text import Tokenizer
# Importação da classe Tokenizer para vetorização de texto e pré-processamento dentro da biblioteca do Keras.

In [ ]:
tokenizer = Tokenizer()
# Criação e ajuste da variável tokenizer.
tokenizer.fit_on_texts(text_sequences)
# Atualiza o tokenizador com base nas sequências de texto fornecidas.

sequences = tokenizer.texts_to_sequences(text_sequences)
# Vetorização das sequências de texto.

In [ ]:
sequences[0]
# Retorna uma lista de números inteiros que representa as palavras da primeira sequência de texto.
# Cada número corresponde ao índice da palavra no vocabulário do tokenizador.

[154,
 6504,
 12941,
 384,
 35,
 751,
 45,
 256,
 804,
 126,
 274,
 129,
 91,
 750,
 340,
 90,
 36,
 48,
 1381,
 6,
 42,
 2575,
 3,
 190,
 396,
 5]

In [ ]:
tokenizer.index_word
# Mapeia os índices das palavras para as próprias palavras.

{1: 'the',
 2: 'of',
 3: 'and',
 4: 'a',
 5: 'to',
 6: 'in',
 7: 'that',
 8: 'his',
 9: 'it',
 10: 'i',
 11: 'he',
 12: 'but',
 13: 'as',
 14: 'was',
 15: 'with',
 16: 'is',
 17: 'for',
 18: 'all',
 19: "'s",
 20: 'at',
 21: 'not',
 22: 'this',
 23: 'be',
 24: 'by',
 25: 'from',
 26: 'him',
 27: 'whale',
 28: 'on',
 29: 'so',
 30: 'you',
 31: 'there',
 32: 'one',
 33: 'had',
 34: 'have',
 35: 'me',
 36: 'or',
 37: 'were',
 38: 'they',
 39: 'what',
 40: 'like',
 41: 'now',
 42: 'my',
 43: "'",
 44: 'which',
 45: 'some',
 46: 'upon',
 47: 'when',
 48: 'no',
 49: 'then',
 50: 'are',
 51: 'their',
 52: 'an',
 53: 'out',
 54: 'more',
 55: 'ship',
 56: 'man',
 57: 'into',
 58: 'up',
 59: 'would',
 60: 'ye',
 61: 'them',
 62: 'if',
 63: 'we',
 64: 'sea',
 65: 'over',
 66: 'do',
 67: 'old',
 68: 'other',
 69: 'captain',
 70: 'who',
 71: 'such',
 72: 'though',
 73: 'been',
 74: 'down',
 75: 'these',
 76: 'ahab',
 77: 'said',
 78: 'yet',
 79: 'any',
 80: 'about',
 81: 'only',
 82: 'will',
 83: '

In [ ]:
tokenizer.word_counts
# Retorna cada palavra encontrada no texto como chave e o número de vezes que a palavra aparece como valor.

OrderedDict([('chapter', 2497),
             ('1', 28),
             ('loomings', 3),
             ('call', 836),
             ('me', 10610),
             ('ishmael', 396),
             ('some', 8717),
             ('years', 1360),
             ('ago', 373),
             ('never', 3468),
             ('mind', 1285),
             ('how', 3340),
             ('long', 4563),
             ('precisely', 404),
             ('having', 977),
             ('little', 4592),
             ('or', 10209),
             ('no', 8572),
             ('money', 227),
             ('in', 59919),
             ('my', 9077),
             ('purse', 126),
             ('and', 90763),
             ('nothing', 1922),
             ('particular', 831),
             ('to', 68588),
             ('interest', 390),
             ('on', 15080),
             ('shore', 468),
             ('i', 33177),
             ('thought', 2964),
             ('would', 6994),
             ('sail', 1404),
             ('about', 5148),
   

In [ ]:
vocabulary_size = len(tokenizer.word_counts)
# Conta o número de elementos no dicionário 'tokenizer.word_counts', que representa as contagens de palavras e armazena o valor na variável.

In [ ]:
import numpy as np
# Importa a biblioteca NumPy.

In [ ]:
sequences = np.array(sequences)
# Converte a variável 'sequences' em um array NumPy.

In [ ]:
sequences
# Retorna a variável 'sequences'.

array([[  154,  6504, 12941, ...,   190,   396,     5],
       [ 6504, 12941,   384, ...,   396,     5,   752],
       [12941,   384,    35, ...,     5,   752,    35],
       ...,
       [    1,  4305,     9, ...,  6503,  1584,   165],
       [ 4305,     9,   159, ...,  1584,   165,   113],
       [    9,   159,  1215, ...,   165,   113,    10]])

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense,LSTM,Embedding,Dropout
# Importação das classes necessárias para construir o modelo LSTM

# Sequential: Essa classe permite criar um modelo sequencial, onde as camadas são organizadas em uma sequência linear, uma após a outra.
# Dense: Essa classe representa uma camada de neurônios totalmente conectada. Ela é usada para adicionar uma camada densa, onde cada neurônio está conectado a todos os neurônios da camada anterior.
# LSTM: Essa classe representa uma camada LSTM, que é um tipo especial de camada em redes neurais recorrentes (RNNs). Ela é especialmente útil para lidar com dados sequenciais, como séries temporais ou texto.
# Embedding: Essa classe é usada para criar representações vetoriais densas para palavras ou tokens. Ela mapeia cada palavra ou token para um vetor de números reais em um espaço vetorial.
# Dropout: Essa classe implementa a técnica de dropout, que é uma forma de regularização usada para evitar overfitting durante o treinamento do modelo. O dropout aleatoriamente desativa um certo número de neurônios durante o treinamento, o que ajuda a evitar a dependência excessiva de neurônios individuais.


In [ ]:
def create_model(vocabulary_size, seq_len):
    #Função para criar um modelo LSTM.

    #Parâmetros - vocabulary_size: O tamanho do vocabulário, ou seja, o número total de palavras únicas no conjunto de dados  e  - seq_len: O comprimento máximo de sequência a ser considerado pelo modelo.

    model = Sequential()
    # Cria uma instância do modelo sequencial.

    model.add(Embedding(vocabulary_size, 25, input_length=seq_len))
    # Adiciona uma camada de embedding ao modelo. A camada de embedding mapeia cada palavra para um vetor de tamanho 25.

    model.add(LSTM(150, return_sequences=True))
    # Adiciona uma camada LSTM ao modelo com 150 unidades. A opção 'return_sequences=True' indica que essa camada retorna sequências em vez de apenas o último estado.

    model.add(LSTM(150))
    # Adiciona uma segunda camada LSTM ao modelo com 150 unidades.

    model.add(Dense(150, activation='relu'))
    # Adiciona uma camada densa (totalmente conectada) ao modelo com 150 unidades e função de ativação ReLU.

    model.add(Dense(vocabulary_size, activation='softmax'))
    # Adiciona uma camada densa de saída com um neurônio para cada palavra do vocabulário e função de ativação softmax.

    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    # Compila o modelo com a função de perda 'categorical_crossentropy', o otimizador 'adam' e a métrica de avaliação 'accuracy'.

    model.summary()
    # Imprime um resumo do modelo, mostrando a arquitetura das camadas e o número de parâmetros.

    return model
    # Retorna o modelo LSTM criado.


In [ ]:
from keras.utils import to_categorical

# Importa uma função que é usada para converter rótulos em um formato especial chamado "one-hot encoding".
# O one-hot encoding é uma forma de representar as classes de um problema de classificação usando vetores binários.
# Ele ajuda a lidar com problemas onde temos várias classes possíveis. A função transforma os rótulos das classes em vetores onde cada classe é representada por um único elemento igual a 1 e todos os outros elementos são iguais a 0. Isso permite que o modelo de aprendizado de máquina trabalhe de forma mais eficiente e faça previsões sobre a probabilidade de cada classe.

In [ ]:
sequences
# Chama a variável 'sequences'.

array([[  154,  6504, 12941, ...,   190,   396,     5],
       [ 6504, 12941,   384, ...,   396,     5,   752],
       [12941,   384,    35, ...,     5,   752,    35],
       ...,
       [    1,  4305,     9, ...,  6503,  1584,   165],
       [ 4305,     9,   159, ...,  1584,   165,   113],
       [    9,   159,  1215, ...,   165,   113,    10]])

In [ ]:
sequences[:,:-1]
# Operação de slicing que retorna uma parte das sequências contidas na variável.
# O : antes da vírgula indica que queremos selecionar todas as linhas das sequências. O :-1 após a vírgula indica que queremos selecionar todas as colunas das sequências, exceto a última coluna.

array([[  154,  6504, 12941, ...,     3,   190,   396],
       [ 6504, 12941,   384, ...,   190,   396,     5],
       [12941,   384,    35, ...,   396,     5,   752],
       ...,
       [    1,  4305,     9, ...,  6502,  6503,  1584],
       [ 4305,     9,   159, ...,  6503,  1584,   165],
       [    9,   159,  1215, ...,  1584,   165,   113]])

In [ ]:
sequences[:,-1]
# Operação de slicing que retorna uma parte das sequências contidas na variável.
# O : antes da vírgula indica que queremos selecionar todas as linhas das sequências. O -1 após a vírgula indica que queremos selecionar a última coluna das sequências.

array([  5, 752,  35, ..., 165, 113,  10])

In [ ]:
X = sequences[:,:-1]
# Coloca a primeira operação de slicing dentro da variável 'X'.

In [ ]:
y = sequences[:,-1]
# Coloca a segunda operação de slicing dentro da variável 'y'.

In [ ]:
y = to_categorical(y, num_classes=vocabulary_size+1)
# Converte o vetor de classes `y` em uma representação categórica usando `to_categorical`.
# Cada classe é codificada como um vetor one-hot.

In [ ]:
seq_len = X.shape[1]
# Obtém o comprimento das sequências na variável `X` usando a propriedade `shape`.
# O valor retornado é a dimensão das sequências (o número de elementos em cada sequência).

In [ ]:
seq_len
# Retorna a variável 'seq_len'.

25

In [ ]:
model = create_model(vocabulary_size+1, seq_len)
# Cria o modelo usando a função `create_model`, passando o tamanho do vocabulário mais 1 e o comprimento das sequências.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 25, 25)            323550    
                                                                 
 lstm (LSTM)                 (None, 25, 150)           105600    
                                                                 
 lstm_1 (LSTM)               (None, 150)               180600    
                                                                 
 dense (Dense)               (None, 150)               22650     
                                                                 
 dense_1 (Dense)             (None, 12942)             1954242   
                                                                 
Total params: 2,586,642
Trainable params: 2,586,642
Non-trainable params: 0
_________________________________________________________________


In [ ]:
from pickle import dump, load
# Importa as funções `dump` e `load` do módulo `pickle`
# A função dump é usada para salvar um objeto Python em um arquivo, permitindo que seja recuperado posteriormente. Ela recebe o objeto a ser salvo e o arquivo onde será armazenado.
# A função load é usada para carregar um objeto previamente salvo em um arquivo. Ela recebe o arquivo e retorna o objeto carregado, que pode ser utilizado no programa.

In [ ]:
model.fit(X, y, batch_size=512, epochs=300, verbose=1)
# Treina o modelo usando os dados de entrada X e os rótulos correspondentes y.
# Utiliza um tamanho de lote de 512 e executa 300 épocas de treinamento.
# Exibe informações de progresso durante o treinamento.



In [ ]:
model.save('./epochBIG.h5')
# Salva o modelo treinado em um arquivo.
# O modelo é salvo em formato .h5.

dump(tokenizer, open('./epochBIG', 'wb'))
# Salva o tokenizer em um arquivo.
# O tokenizer é salvo usando a biblioteca pickle em formato binário (.pkl).

In [ ]:
from random import randint
# Importa a função randint da biblioteca random.

from pickle import load
# Importa a função load da biblioteca pickle para carregar o tokenizer e o modelo.

from keras.models import load_model
# Importa a função load_model da biblioteca keras.models para carregar o modelo treinado.

from keras.preprocessing.sequence import pad_sequences
# Importa a função pad_sequences da biblioteca keras.preprocessing.sequence.
# Essa função é usada para fazer o preenchimento (padding) das sequências com zeros.

In [ ]:
def generate_text(model, tokenizer, seq_len, seed_text, num_gen_words):
    #Função que gera texto usando um modelo treinado.

    #Parâmetros:
    - model: Modelo treinado com os dados de texto.
    - tokenizer: Tokenizer que foi ajustado com os dados de texto.
    - seq_len: Comprimento da sequência de treinamento.
    - seed_text: Texto inicial para servir como base.
    - num_gen_words: Número de palavras a serem geradas pelo modelo.

    output_text = []
    # Saída final

    input_text = seed_text
     # Sequência inicial

    for i in range(num_gen_words):
        # Criação do texto gerado

        encoded_text = tokenizer.texts_to_sequences([input_text])[0]
         # Converte o texto de entrada em uma sequência codificada

        pad_encoded = pad_sequences([encoded_text], maxlen=seq_len, truncating='pre')
        # Preenche as sequências de acordo com o comprimento de treinamento (seq_len)

        pred_word_ind = model.predict_classes(pad_encoded, verbose=0)[0]
        # Prediz as probabilidades de classe para cada palavra

        pred_word = tokenizer.index_word[pred_word_ind]
        # Obtém a palavra prevista

        input_text += ' ' + pred_word
        # Atualiza a sequência de texto de entrada (deslocando uma palavra com a nova palavra)

        output_text.append(pred_word)
        # Adiciona a palavra prevista 'pred_word' à lista 'output_text'

    # Retorna o texto gerado como uma única string
    return ' '.join(output_text)


In [ ]:
text_sequences[0]
# Retorna a primeira sequência de texto armazenada na lista 'text_sequences'

In [ ]:
import random
# Importa a biblioteca Random

random.seed(101)
# Define uma seed para garantir a reprodutibilidade dos resultados

random_pick = random.randint(0, len(text_sequences))
# Gera um número inteiro aleatório entre 0 e o tamanho da lista text_sequences

In [ ]:
random_seed_text = text_sequences[random_pick]
# Seleciona uma sequência aleatória da variável 'text_sequences' usando o índice 'random_pick'

In [ ]:
random_seed_text
# Retorna a variável 'random_seed_text'

In [ ]:
seed_text = ' '.join(random_seed_text)
# Cria uma string 'seed_text' a partir da lista de tokens 'random_seed_text' usando a função 'join()', resultando em uma sequência de texto que será usada como seed para a geração de texto pelo modelo

In [ ]:
seed_text
# Retorna a variável 'seed_text'

In [ ]:
generate_text(model,tokenizer,seq_len,seed_text=seed_text,num_gen_words=50)
# Gera um texto com base nos parâmetros fornecidos:
# Model: O modelo treinado usado para gerar o texto.
# Tokenizer: O tokenizer usado durante o treinamento do modelo.
# Seq_len: O comprimento da sequência usada durante o treinamento do modelo.
# Seed_text: O texto inicial usado como semente para a geração de texto. Pode ser fornecido como um argumento opcional.
# Num_gen_words: O número de palavras a serem geradas pelo modelo.

In [ ]:
full_text = read_file('/content/melville-moby_dick.txt')
# Armazena o conteúdo do arquiva na variável 'full_text'

In [ ]:
for i, word in enumerate(full_text.split()):
    if word == 'inkling':
      # Percorre cada palavra do texto e verifica se é igual a 'inkling'.

        print(' '.join(full_text.split()[i-20:i+20]))
        print('\n')
        # Retorna as palavras antes e depois de 'inkling'.
        # Obtém a lista completa de palavras do texto dividido pelo espaço em branco.
        # Seleciona um intervalo de 20 palavras antes e depois de 'inkling'.
        # Concatena as palavras selecionadas em uma única string, separadas por espaço.
        # Retorna a string resultante.

In [ ]:
# Integrantes
# Cesar Oliveira Goes - RM: 98119
# Fiama dos Santos Trajano - RM: 97885
# Gabriel Silva de Negreiros Leal da Rocha - RM: 550759
# Karina Maciel Palmeira - RM: 551770